import Head from "next/head";
import { DefaultLayout } from "../Components/Layout/default";
import { Text, Flex } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nestor Macedo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex marginInline={["2rem", "2rem","10rem"]} flexDirection="column">
          <Text fontSize="43px" lineHeight="50px" fontWeight="bold">
            Nestor Macedo
          </Text>
          <Text fontWeight="thin" fontSize="35px">
            Front-end Developer
          </Text>
          <Text>Um estudante de programação procurando uma oportunidade.</Text>
        </Flex>
      </DefaultLayout>
    </>
  );
}
